ClientEvents.lang("en_us", event => {
    event.renameItem('spelunkery:salt', 'Salt Dust')
    event.renameItem('galosphere:pink_salt_shard', 'Salt Crystal')
    event.renameItem('galosphere:pink_salt_straw', 'Salt Straw')
    event.renameItem('vintagedelight:smooth_salt_block', 'Composite Salt Block')
    event.renameItem('vintagedelight:salt_pillar', 'Composite Salt Pillar')
    event.renameItem('vintagedelight:salt_brick_wall', 'Composite Salt Brick Wall')
    event.renameItem('vintagedelight:salt_brick_stairs', 'Composite Salt Brick Stairs')
    event.renameItem('vintagedelight:salt_brick_slab', 'Composite Salt Brick Slab')
    event.renameItem('vintagedelight:salt_bricks', 'Composite Salt Bricks')
    event.renameItem('spelunkery:rock_salt_block', 'Salt Crystal Block')
    event.renameItem('spelunkery:rock_salt_stairs', 'Salt Crystal Stairs')
    event.renameItem('spelunkery:rock_salt_slab', 'Salt Crystal Slab')
    event.renameItem('spelunkery:rock_salt_wall', 'Salt Crystal Wall')
    event.renameItem('spelunkery:polished_rock_salt', 'Polished Salt Crystal Block')
    event.renameItem('spelunkery:polished_rock_salt_stairs', 'Polished Salt Crystal Stairs')
    event.renameItem('spelunkery:polished_rock_salt_slab', 'Polished Salt Crystal Slab')
    event.renameItem('spelunkery:polished_rock_salt_wall', 'Polished Salt Crystal Wall')
    event.renameItem('spelunkery:rock_salt_bricks', 'Polished Salt Crystal Bricks')
    event.renameItem('spelunkery:rock_salt_brick_stairs', 'Polished Salt Crystal Brick Stairs')
    event.renameItem('spelunkery:rock_salt_brick_slab', 'Polished Salt Crystal Brick Slab')
    event.renameItem('spelunkery:rock_salt_brick_wall', 'Polished Salt Crystal Brick Wall')
})