#Hard disable entire modules. Use at your own risk and don't ask for support if you use this
#Thu Dec 19 10:29:20 EST 2024
farmersdelight=true
twigs=true
quark=true
friendsandfoes=true
refurbished_furniture=true
